version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - database.env # configure postgres