keycloak:
  url: https://auth.ramifica.eu
  realm: master
  username: admin
  password: passwd
  clientName: admin-cli

spring:
  datasource:
    url: jdbc:postgresql://connect-db.cndzik9fvw56.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: PDeODShSa4DmsN6MQxd8
management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always

ramifica:
  web-socket:
    enabled: true
