spring:
  datasource:
    username: connect
    password: magic
    url: jdbc:postgresql://localhost:5432/connect

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  data:
    rest:
      default-media-type: application/json

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://alb-keycloak-1028309459.us-east-1.elb.amazonaws.com:8080/realms/master
  sql:
    init:
      mode: always
server:
  servlet:
    encoding:
      enabled: true

springdoc.swagger-ui.path: "/swagger-ui.html"




