spring:
  jpa:
    show-sql: false
  datasource:
    url: jdbc:postgresql://connect-db.cndzik9fvw56.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: PDeODShSa4DmsN6MQxd8
management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always

ramifica:
  web-socket:
    enabled: true
    secured: true
  mail:
    enabled: true
    unread-notification: true
