spring:
  datasource:
    url: jdbc:postgresql://connect-db.cndzik9fvw56.us-east-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://alb-keycloak-1028309459.us-east-1.elb.amazonaws.com:8080/auth/realms/master
management:
  endpoint:
    health:
      show-details: always
