keycloak:
  url: http://localhost:28080
  realm: master
  username: admin
  password: passwd
  clientName: admin-cli

spring:
  datasource:
    username: connect
    password: magic
    url: jdbc:postgresql://localhost:5432/connect

  liquibase:
    change-log: db/changelog/db.changelog-master.xml
  data:
    rest:
      default-media-type: application/json
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.url}/auth/realms/${keycloak.realm}
  mail:
    host: email-smtp.us-east-1.amazonaws.com
    port: 587
    username: AKIA4FIQLIEEDSYVNYW7
    password: BGuI+KOEGe9+O2Y0mN/OVR8xAx1kySUpSvbfHtmN2KWk
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  servlet:
    encoding:
      enabled: true

springdoc.swagger-ui.path: "/swagger-ui.html"
management:
  health:
    mail:
      enabled: false
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

aws:
  s3:
    files-bucket: ramifica-files

ramifica:
  web-socket:
    enabled: true
    secured: true
  mail:
    enabled: true
