package com.nabagagem.connectbe.domain.exceptions;

public enum ErrorType {
    INVALID_PROFILE_PIC_FORMAT, EVENT_NOT_FOUND, REPORT_NOT_FOUND, UNIQUE_VALUE, EMAIL_ALREADY_EXISTS, INVALID_PROFILE_PIC_SIZE,
    MISSING_OTHER_CATEGORY, THREAD_BLOCKED_BY_ANOTHER_USER, MESSAGE_CANNOT_BE_READ, THREAD_BLOCKED,
    INVALID_PARENT_PROFILE
}
