package com.nabagagem.connectbe.domain.job;

public enum JobCategory {
    IT,
    DESIGN_MULTIMEDIA,
    TRANSLATIONS_CONTENT,
    MARKETING_SALES,
    BEAUTY_CARE,
    MGMT_ADVICE,
    ARTS_CRAFTSMANSHIP,
    PET_SITTER,
    PET_CARE,
    BABY_SITTER,
    HAUS_KEEPING,
    GARDENING,
    LANGUAGE_GERMAN,
    LANGUAGE_ENGLISH,
    MUSICIAN,
    MUSIC_TEACHER,
    LANGUAGE_OTHER,
    OVERALL_MAINTENANCE,
    OTHER
}
